services:
  db:
    build:
      context: ./
      dockerfile: dockerfile.pg
    ports:
      - "5432:5432"
    # volumes:
    #   - db-data:/var/lib/postgresql/data
  cache:
    build:
      context: ./
      dockerfile: dockerfile.redis
    ports:
      - "6379:6379"
      # - "8001:8001"
    # volumes:
    #   - cache-data:/data

# volumes:
#   db-data:
#   cache-data:
